"""Policies package initialization."""
from src.domain.policies.policy_rules import (
    DEFAULT_BLACKLIST_RULES,
    is_target_authorized,
    PATTERN_MASS_DELETION,
    PATTERN_DISK_FORMATTING,
    PATTERN_PARTITION_AND_RAW_WRITES,
    PATTERN_SYSTEM_SHUTDOWN,
    PATTERN_HOST_FIREWALL_TAMPERING,
)

__all__ = [
    "DEFAULT_BLACKLIST_RULES",
    "is_target_authorized",
    "PATTERN_MASS_DELETION",
    "PATTERN_DISK_FORMATTING",
    "PATTERN_PARTITION_AND_RAW_WRITES",
    "PATTERN_SYSTEM_SHUTDOWN",
    "PATTERN_HOST_FIREWALL_TAMPERING",
]
